### ISSUE TITLE
Add additional logic to determine if an item is renewable (and a user is eligible to renew it..)

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#291] opened 2019-07-27 17:32 UTC
Renewing checkouts is governed by information in the circrule and circrecord.  Note: Symphony WorkFlows language refers to user renewals as "unseen renewals" in the WorkFlows app. (Staff renewals - when the book is present - are referred to as "seen".  MyLibrary should only ever be renewing materials as "unseen".)

To determine if a checkout is renewable, the following needs to be true in Symphony:
- [ ] User status = OK or DELINQUENT
- [ ] "today" needs to be within the number of days set in the CircRule for "only allow unseen renewals within this number of days before the due date".   
-- I think this is "renewFromPeriod" (Shelley confirmed)
- [ ] Item has no holds/recalls (TITLE or COPY) 
- [ ] Item isn't claims returned
- [ ] Item isn't assumed lost
- [ ] Unseen renewals remaining = more than 0

We'll also show the user why an item isn't renewable in the expanding details.

**Comment by shelleydoljack** [comment] 2019-07-27 22:18
I now wonder if MyLibrary is doing seen renewals because we log in to web services as a staff user that is mapped to the Symphony interface web services staff.

Yes, it’s the renewFromPeriod.

I suspect we might want to do the ItemCircInfo advise action to determine the other parts of renew ability (is there a hold, etc.)

**Comment by shelleydoljack** [comment] 2019-07-29 18:15
I just confirmed that the `unseenRenewalsRemaining` counter does update when renewing an item in MyLibrary. 😌  The counter went from 2 to 1 for the title `Teapots and tea` for SUPER3.

**Comment by saseestone** [comment] 2019-07-29 18:29
🙌🏼

**Comment by jgreben** [comment] 2019-08-01 21:36
Fixed by #400

**Closed** 2019-08-02 15:09 UTC
