### ISSUE TITLE
Fix Test Error Where Build Fails when run between 11:18 pm and 12:00 am

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/mylibrary#304] opened 2019-07-29 16:00 UTC
At 11:18 pm until 11:59 pm Time.zone.now + 42 minutes will no longer be "Today"

Failures:
  1) ApplicationHelper#today_with_time_or_date when the checkout is a short term loan returns a string that says Today and the time
     Failure/Error:
       expect(helper.today_with_time_or_date(Time.zone.now + 42.minutes, short_term: true))
         .to match(/^Today at\s{1,2}\d/)
     
       expected "Tomorrow" to match /^Today at\s{1,2}\d/
       Diff:
       @@ -1,2 +1,2 @@
       -/^Today at\s{1,2}\d/
       +"Tomorrow"
       
    ./spec/helpers/application_helper_spec.rb:19

**Comment by cbeer** [comment] 2019-07-29 16:00
Duplicate of #303?

**Closed by cbeer** 2019-07-29 16:00 UTC
