### ISSUE TITLE
[mylibrary/prod] FolioClient::IlsError: Renew request for was not successful. status: 422, {  "errors" : [ {    "message" : "Items with this loan policy cannot be renewed when there is an active, pending hold request",    "parameters" : [ {      "key" : "loanPolicyName",      "value" : "28day-2renew-7daygrace"    }, {      "key" : "loanPolicyId",      "value" : "3efe7693-3357-4f9b-999d-a271f86019b0"    }...

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#1083] opened 2024-04-08 15:54 UTC
## Backtrace

    line 283 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 130 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item_by_id
    line 15 of [PROJECT_ROOT]/app/controllers/renewals_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/106769649)

**Comment by corylown** [comment] 2024-06-12 19:57
There are at least two different problems contributing to these errors.

1. The first case is that we were not checking for holds that are not recalls. Should be fixed by: https://github.com/sul-dlss/mylibrary/pull/1104
2. The second case appears to be caused by duplicate POST requests to the /renewals/all_eligible route within about 30 seconds of each other. So my assumption is that the items are eligible for renewal before the first POST and the errors are the result of the second POST request when FOLIO has already renewed the items. We may be able to prevent this by disabling the renew buttons after they are clicked and adding a spinner to show something is happening.

**Comment by corylown** [comment] 2024-06-19 14:06
Closing this since I haven't seen any of these errors reported since the fixes above were applied on Monday.

**Closed by corylown** 2024-06-19 14:06 UTC
